import "./globals.css";
import { Raleway } from "next/font/google";
import AuthProvider from "./context/authContext";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={raleway.className}>
                <AuthProvider>{children} </AuthProvider>
            </body>
        </html>
    );
}
